name = "zkLean"
version = "0.1.0"
defaultTargets = ["zklean"]

[[lean_lib]]
name = "ZkLean"

[[lean_exe]]
name = "zklean"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0-rc4"


[[require]]
name = "auto"
git = "https://github.com/leanprover-community/lean-auto"
rev = "main"
