name = "zkLean"
version = "0.1.0"
defaultTargets = ["zklean"]

[[lean_lib]]
name = "ZkLean"

[[lean_exe]]
name = "zklean"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "8448d4bb7aab7998632383c7a71975fecab9a9ee"
