name = "zkLean"
version = "0.1.0"
defaultTargets = ["zklean"]

[[lean_lib]]
name = "ZkLean"

[[lean_exe]]
name = "zklean"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.21.0"


[[require]]
name = "auto"
git = "https://github.com/leanprover-community/lean-auto"
rev = "32b0e4d"

[[require]]
name = "mpl"
git = "https://github.com/sgraf812/mpl"
rev = "52e8300"